### ISSUE TITLE
能否直接屏蔽“欢迎回来”

### ISSUE THREAD

**Issue by oOtroyOo** [Xposed-Modules-Repo/com.skyhand.sinahelper#3]
有时候打开刚主页，或者说是从通知栏打开了一条感兴趣的帖子。
因为有段时间没登陆，他显示了“欢迎回来”页面和“推荐博主”页面。
“欢迎回来”还好，有个跳过键，“推荐博主”页面则默认勾选了一些从来不认识的人，还要多点几下取消勾选、确定进入，烦啊
而最头疼的是，这些都跳过了之后。回到首页后，他会刷新首页，导致刚才点击的帖子就不见了。

**Comment by oOtroyOo** [comment]
补充一句，我用的是2.1.5，因为是xposed平台里的版本，不想轻易更新，如果后续版本已经加了这个功能，就关闭issue吧。

**Comment by tpnet** [comment]
您好，暂时不考虑屏蔽 欢迎回来，因为这个出现的频率太低了。 然后新版本猪手有短微博浏览历史功能。
